sonar.projectKey=ssd-practical-test
sonar.projectName=SSD Practical Test
sonar.projectVersion=1.0
sonar.sources=src,public
sonar.tests=test
sonar.test.inclusions=test/**/*.test.js
sonar.exclusions=node_modules/**,reports/**,certs/**,.scannerwork/**
sonar.sourceEncoding=UTF-8
